### ISSUE TITLE
I have filed a DMCA

### ISSUE THREAD

**Issue by ShinyHobo** [iceriny/QuickLocalizationAids#1]
As per my message here, https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/130, do not distribute derivative copies of my code. My code is not licensed for such use.

Feel free to contribute to the native localization efforts directly.

**Comment by iceriny** [comment]
I replied with the same content on Nexus:

"Oh no! I checked GitHub at that time and didn't come across your response. I apologize for that. Of course, I can provide the translation for you.

However, it's worth mentioning that if you've looked at my project's GitHub page, you might notice traces of your code, but I have made extensive modifications to the majority of it and added more code content. There's no denying that much of it was inspired by your code. I am a self-taught amateur enthusiast of C#, and this tool is mainly geared towards translation work rather than moderation. Going forward, I intend to gradually rewrite and organize the code to better serve translators.

Regardless, if this truly makes you uncomfortable, I am willing to remove this tool.

Good luck!"

After seeing your message, I felt quite anxious. I lack experience in dealing with such matters, and this is even my first practical program. I'm not sure if this kind of thing is permissible. I look forward to your response.

**Comment by ShinyHobo** [comment]
It is not; if you wish to extend the functionality of my code, please do so by forking the repository and submitting pull requests to it. I put quite a bit of effort into making the app localization friendly and easy for you to update after your request. I don't wish to alienate non-English speakers or prevent them from being able to use my application.

**Comment by iceriny** [comment]
Additional information: Since it appears that I can only receive your responses here, I will close down the project after receiving your reply. Furthermore, I have already hidden the tool on Nexus.

**Comment by iceriny** [comment]
Regarding the contact information, of course, I wouldn't want to be a bother! Haha, I was simply considering the possibility of making a friend—albeit in what seems to be a somewhat unusual manner (😄). Additionally, having an international friend is pretty cool—especially considering that, for various reasons, China's internet isn't always well-connected with other regions! And, there's one more thing! There might be some questions about localization tasks that I'll have, but I'll definitely only reach out after exhaustively researching on my own and not finding any solutions.

**Comment by ShinyHobo** [comment]
> So, if I understand correctly, does that mean my project cannot be published and shared for everyone to use? Unless I rewrite all of the code without including your code?

Correct. I'm sorry, I know it is a pain.

> If possible, could you provide an alternative way to contact you? For instance, I'm not sure, perhaps a instant messaging application like Telegram? Is that a possibility?

My discord handle is shinyhobo and I am in the Larian discord server: https://discord.com/invite/larianstudios
